default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV["TURSO_DATABASE_URL"]
               &.gsub("libsql://", "")
               &.concat("?authToken=#{ENV["TURSO_AUTH_TOKEN"]}") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
