default: &default
  adapter: libsql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['TURSO_DATABASE_URL'] %>
  auth_token: <%= ENV['TURSO_AUTH_TOKEN'] %>

development:
  <<: *default
  database: wizzle_development

test:
  <<: *default
  database: wizzle_test

production:
  <<: *default
  database: wizzle_production